from django.shortcuts import render
from django.http import JsonResponse,HttpResponse
from django.utils.http import is_safe_url
from billing.models import BillingProfile
from accounts.models import GuestEmail
from django.shortcuts import redirect

import stripe
stripe.api_key = "sk_test_51HRwMeEcligTwCtGTBzUurE2xEXgFforhjIu7PKZp4fFFd5SH0jQeihxfWuRKwmR87GN615oWDINevLx3jDw80an00JgigGJag"
STRIPE_PUBLISHABLE_KEY = "pk_test_51HRwMeEcligTwCtGrB70qW1aPm94C4P6f8U3Mdo8CJ1mYFRJau5OH0zeFGq3CXmeGYZ7taXrRKTJwCQGcR5krfpL00jlRIytcR"

# Create your views here.
def payment_method_view(request):
    current_user = request.user
    print(request.session)
    guest_email_id = request.session.get("guest_email_id")
    billing_profile = None
    billing_profile_iscreated = False
    
    
    if current_user.is_authenticated:
        billing_profile,billing_profile_iscreated = BillingProfile.objects.get_or_create(user=current_user,email=current_user.email)
    elif guest_email_id is not None:
        guest_email_object = GuestEmail.objects.get(id=guest_email_id)
        billing_profile,billing_profile_iscreated = BillingProfile.objects.get_or_create(email=guest_email_object.email)
    else:
        pass
    
    if billing_profile is not None:
        current_billing_profile = billing_profile
        current_customer_id = current_billing_profile.customer_id
        print("billing profile is not none")
        print(current_customer_id)
    else:
        print("billing profile is None")
        return redirect("/cart/")
    
    nextURL = None
    next_ = request.GET.get('next')
    print("next url: ")
    print(next_)
    
    if is_safe_url(next_ ,request.get_host()):
        nextURL = next_
    
    
    context = {"stripe_publishable_key":STRIPE_PUBLISHABLE_KEY,"nextURL":nextURL}
   
    if request.method == "POST":
        print(request.POST)
    return render(request, "paymentmethod.html", context)

def payment_method_createview(request):
    current_user = request.user
    print(request.session)
    guest_email_id = request.session.get("guest_email_id")
    billing_profile = None
    billing_profile_iscreated = False
    
    if request.method == "POST" and request.is_ajax:
        print(request.POST)
        if current_user.is_authenticated:
            billing_profile,billing_profile_iscreated = BillingProfile.objects.get_or_create(user=current_user,email=current_user.email)
        elif guest_email_id is not None:
            guest_email_object = GuestEmail.objects.get(id=guest_email_id)
            billing_profile,billing_profile_iscreated = BillingProfile.objects.get_or_create(email=guest_email_object.email)
        else:
            pass
        
    if billing_profile is not None:
        token = request.POST.get("token")
        #When create a new card, must specify a customer on which to create it: https://stripe.com/docs/api/cards/create
        if token is not None:
        #two parameters: customer id && source(which is the card token generated by stripe)
           responese =  stripe.Customer.create_source(billing_profile.customer_id,source=token,)
           print(responese)
           return JsonResponse({"message":"Card added"})
    else:
        return HttpResponse("you are not authorized to visit this page",status=401)
    
    
    
    return JsonResponse({"message":"Card added"})
            
        
        
        
        
    